# Generated by Django 3.0.4 on 2020-04-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitaleraapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='digitaleraapp.BusinessInfo'),
        ),
        migrations.AddField(
            model_name='email',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='digitaleraapp.BusinessInfo'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessInfos', to=settings.AUTH_USER_MODEL),
        ),
    ]
