# Generated by Django 3.0.4 on 2020-03-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0002_businessinfo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='image_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
