# Generated by Django 3.0.4 on 2020-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0002_auto_20200406_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('LETTER', 'Letter'), ('PITCH', 'Pitch presentation')], default='EMAIL', max_length=6),
        ),
    ]
