# Generated by Django 3.0.4 on 2020-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0003_auto_20200327_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
