# Generated by Django 3.0.4 on 2020-03-27 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0004_auto_20200327_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_number', models.CharField(max_length=30)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='digitaleraapp.BusinessInfo')),
            ],
        ),
    ]
