# Generated by Django 3.0.4 on 2020-03-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0006_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePerformanceAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('overall_savings_ms', models.DecimalField(decimal_places=2, max_digits=15)),
                ('display_value', models.CharField(max_length=300)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_audits', to='digitaleraapp.BusinessInfo')),
            ],
        ),
    ]
