# Generated by Django 3.0.4 on 2020-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0007_websiteperformanceaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteperformanceaudit',
            name='display_value',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='websiteperformanceaudit',
            name='overall_savings_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
