# Generated by Django 3.0.4 on 2020-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitaleraapp', '0008_auto_20200328_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteperformanceaudit',
            name='overall_savings_ms',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20),
        ),
    ]
